### ISSUE TITLE
godebug should be aware of identifiers in the package block

### ISSUE THREAD

**Issue by jeremyschlatter** [mailgun/godebug#11]
Currently it is only aware of identifiers in function body and block statement scopes

**Comment by rambocoder** [comment]
@jeremyschlatter you mean variables and consts outside of function bodies?

```
package blah
const c = 10  // doing
var x string
func fun(){
_ = "breakpoint" // doing h c OR h x does not print their values
}
```

**Comment by jeremyschlatter** [comment]
@rambocoder exactly

Also, when godebug gains the ability to evaluate expressions it would be nice to refer to function names and imported identifiers.
