### ISSUE TITLE
declarations only used inside subsequently defined closures problematic: error "printf.go:485:6: argType declared but not used"

### ISSUE THREAD

**Issue by glycerine** [mailgun/godebug#14]
Tried running godebug on my light fork of Ross' c2go. It errored out on un-used declaration. The declaration is used, but only inside a closure defined later in that function.

prep:
go get github.com/glycerine/c2go

~~~
jaten@mbp13:~/go/src/github.com/glycerine/c2go$ godebug run *.go
printf.go:485:6: argType declared but not used
couldn't load packages due to errors: main
jaten@mbp13:~/go/src/github.com/glycerine/c2go$ 
~~~

minimal test case small.go:
~~~
package main

func takeClosure(f func(i interface{})) {
}

func main() {
    var touchedInClosure string
    takeClosure(func(i interface{}) {
        switch i.(type) {
        case string:
            touchedInClosure = "I have been written to!"
        }
    })
}
~~~
results on minimal test case small.go
~~~
jaten@mbp13:~/go/src/github.com/glycerine/c2go$ godebug run small.go
small.go:7:6: touchedInClosure declared but not used
couldn't load packages due to errors: main
jaten@mbp13:~/go/src/github.com/glycerine/c2go$ 
~~~

c2go is probably a nice small-medium sized program to try godebug on; I would suggest confirming that godebug works on it in full.

**Comment by jeremyschlatter** [comment]
Thanks for the report! Surprisingly, it looks like you found a bug in `golang.org/x/tools/go/loader`:

Minimal loader program loader.go:

    package main

    import (
        "fmt"

        "golang.org/x/tools/go/loader"
    )

    func main() {
        var conf loader.Config
        conf.CreateFromFilenames("main", "small.go")
        _, err := conf.Load()
        fmt.Println(err)
    }

results on your minimal test case small.go

    $ go run loader.go
    small.go:7:6: touchedInClosure declared but not used
    couldn't load packages due to errors: main

I'll see if I can find out what's going on and get this fixed upstream.

**Comment by omeid** [comment]
This isn't a bug. Using a variable isn't just writing to it but reading it and because the variable is never used inside it's scope, it complains about it.

**Comment by jeremyschlatter** [comment]
@omeid is right. It's unfortunate that godebug does not accept a program that the go tool does, though.

I was curious what the spec had to say about this. I found [this](https://golang.org/ref/spec#Variable_declarations):

> Implementation restriction: A compiler may make it illegal to declare a variable inside a function body if the variable is never used.

So the spec leaves this open, and both the go tool and the loader library are in compliance. The latter is just more strict.

**Comment by jeremyschlatter** [comment]
Early versions of godebug used `golang.org/x/tools/go/types` for type checking. That library does not object to small.go:

    package main

    import (
        "fmt"
        "go/ast"
        "go/parser"
        "go/token"

        "golang.org/x/tools/go/types"
    )

    func main() {
        var fs token.FileSet
        f, err := parser.ParseFile(&fs, "small.go", nil, 0)
        if err != nil {
            fmt.Println("error in parsing: ", err)
            return
        }
        _, err = types.Check("main", &fs, []*ast.File{f})
        fmt.Println(err)
    }

Running it:

    $ go run parser.go
    <nil>

The loader library provides a lot that the types library does not, so it might not be worth the effort to switch to it. But it would make godebug behave more like go for this case.

**Comment by omeid** [comment]
Please don't downgrade.

**c2go** has been written against an older version of Go and should be ported to the latest if they want to use **godebug**, not the other way around.

**Comment by jeremyschlatter** [comment]
c2go isn't outdated. It runs on tip (or, at least, my copy of tip from last week):

    ~/src/github.com/glycerine/c2go$ go version
    go version devel +180fbb1 Fri Mar 27 00:30:14 2015 +0000 linux/amd64
    ~/src/github.com/glycerine/c2go$ go run *.go
    usage: c2go [options] *.c
      -I string
    	    include directory
      -c string
    	    config file
      -dst string
    	    GOPATH root of destination (default "/tmp/c2go")
    exit status 2

The surprising behavior is that `godebug`'s type checker behaves differently from `go`'s type checker, even though both are compliant with the language spec.

**Comment by jeremyschlatter** [comment]
@glycerine I tried just deleting that variable from the code and `godebug run` worked fine:

    $ godebug run *.go
    usage: c2go [options] *.c
      -I="": include directory
      -c="": config file
      -dst="/tmp/c2go": GOPATH root of destination

**Comment by jeremyschlatter** [comment]
Oops, I messed up my test with `golang.org/x/tools/go/types`. I had edited small.go before I ran the test. Running again with the original file, it gives the same error as the loader library:

    $ go run parser.go
    small.go:7:6: touchedInClosure declared but not used

I'm going to call this one `wontfix`. Sorry, @glycerine! If you want to debug that library, just delete that variable.

**Comment by glycerine** [comment]
Arg. Agree we can't fix this locally, but I am still inclined to think we
should upstream this as an issue so that "go run" and the types library are
consistent.

On Sun, Apr 5, 2015 at 9:58 PM, Jeremy Schlatter <notifications@github.com>
wrote:

> Closed #14 <https://github.com/mailgun/godebug/issues/14>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mailgun/godebug/issues/14#event-273861199>.
>



-- 

Best regards,
Jason

--
Jason E. Aten, Ph.D.
j.e.aten@gmail.com
650-429-8602
linkedin: https://www.linkedin.com/pub/jason-e-aten-ph-d/18/313/45a

**Comment by glycerine** [comment]
err, I misread -- It's the "golang.org/x/tools/go/loader" library that
differs in strictness, yes?

On Mon, Apr 6, 2015 at 7:55 AM, Jason E. Aten <j.e.aten@gmail.com> wrote:

> Arg. Agree we can't fix this locally, but I am still inclined to think we
> should upstream this as an issue so that "go run" and the types library are
> consistent.
>
> On Sun, Apr 5, 2015 at 9:58 PM, Jeremy Schlatter <notifications@github.com
> > wrote:
>
>> Closed #14 <https://github.com/mailgun/godebug/issues/14>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mailgun/godebug/issues/14#event-273861199>.
>>
>
>
>
> --
>
> Best regards,
> Jason
>
> --
> Jason E. Aten, Ph.D.
> j.e.aten@gmail.com
> 650-429-8602
> linkedin: https://www.linkedin.com/pub/jason-e-aten-ph-d/18/313/45a
>



-- 

Best regards,
Jason

--
Jason E. Aten, Ph.D.
j.e.aten@gmail.com
650-429-8602
linkedin: https://www.linkedin.com/pub/jason-e-aten-ph-d/18/313/45a

**Comment by glycerine** [comment]
opened https://github.com/golang/go/issues/10356 to track upstream

**Comment by jeremyschlatter** [comment]
go/loader and go/types behave the same way, and both are different from gc. I thought differently earlier in the ticket, but I was mistaken.
