### ISSUE TITLE
malformed fp constant exponent

### ISSUE THREAD

**Issue by dcu** [mailgun/godebug#16]
I was trying godebug out with one of my projects today and I got this error message:

    /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:11: malformed fp constant exponent
    /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:11: syntax error: unexpected literal 1p, expecting name or (
    /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:11: malformed fp constant exponent
    /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:18: malformed fp constant exponent
    /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:18: syntax error: unexpected name, expecting )
    /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:20: malformed fp constant exponent
    /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:20: syntax error: unexpected name, expecting semicolon or newline or }
    /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:66: malformed fp constant exponent
   /var/folders/t9/9tt1kghs13qb57tn266lwmzd957b86/T/godebug040698979/1p.go:66: syntax error: unexpected literal 1p, expecting name or (

any ideas?

    $ go version
    go version go1.4.2 darwin/amd64

**Comment by dcu** [comment]
I found the issue, it's because the program starts with a number

**Comment by jeremyschlatter** [comment]
Ah, that makes sense. I know where the bug is. I'll fix it shortly.

**Comment by jeremyschlatter** [comment]
Thanks for reporting it!

**Comment by jeremyschlatter** [comment]
Should be fixed in 77636161ee217cca20a349a0c64fddad7a99d1e8. Does it work for you now?

**Comment by jeremyschlatter** [comment]
@dcu ^

**Comment by dcu** [comment]
@jeremyschlatter Yeah I confirm it works fine.

Do you think it's possible to use something like https://github.com/sbinet/go-eval to evaluate expressions?

**Comment by jeremyschlatter** [comment]
@dcu Thanks for the pointer to go-eval. Yes, I definitely want to integrate something like that soon. See #10 and #18
