### ISSUE TITLE
Is it possible to dereference pointers?

### ISSUE THREAD

**Issue by nealsanche** [mailgun/godebug#18]
I tried `p *ptrVar` but that didn't work, and I expected it would.

**Comment by jeremyschlatter** [comment]
godebug can only evaluate variable names right now. I want to add pointer dereferencing and other expressions soon. See #10

**Comment by jeremyschlatter** [comment]
@nealsanche This is now fixed!

**Comment by nealsanche** [comment]
Great. I'll have a look. Thanks.
On Jul 11, 2015 10:45 PM, "Jeremy Schlatter" <notifications@github.com>
wrote:

> @nealsanche <https://github.com/nealsanche> This is now fixed!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mailgun/godebug/issues/18#issuecomment-120686922>.
>

-- 
Robots and Pencils Inc | 1507 14th Ave SW Calgary AB T3C 0W4
You can unsubscribe from the Robots and Pencils mailing lists by clicking 
here. <https://robotsandpencils.com/contact/unsubscribe.html>
