### ISSUE TITLE
undefined: scope

### ISSUE THREAD

**Issue by dcu** [mailgun/godebug#20]
The following program doesn't work:

    package main
    import (
    	"os"
    )
    func main() {
    	if o := os.Getenv("O"); o != "" {
    		println(o)
    	} else if s := os.Getenv("S"); s != "" {
    		println(s)
    	}
    }

**Comment by jeremyschlatter** [comment]
Thanks for the report! Fixing now.

**Comment by jeremyschlatter** [comment]
Fixed in bc74b8dafd779a8ebdda5742aca1ff0cacd63d8f
