### ISSUE TITLE
Allow to build/run packages, not only lists of go files

### ISSUE THREAD

**Issue by FiloSottile** [mailgun/godebug#30]

**Comment by FiloSottile** [comment]
How I see this working is with build accepting a package name and run a file name.

That should account for most uses, while being a lot simpler on the UX.

**Comment by FiloSottile** [comment]
Here's a sketch of a usage I'll look at implementing:

```
godebug build [-godebugwork] [-instrument pkgs...] [-o output] package
    Takes a single main package. If arguments are a list of *.go files they
    are treated as a single package. -o as in go build with .debug suffix.
godebug run [-godebugwork] [-instrument pkgs...] gofiles... [--] [arguments...]
    Compile and run the given set of *.go files as a main package.
godebug test [-godebugwork] [-instrument pkgs...] [-c] [-o output] [packages] [flags for test binary]
    -c, -o, packages and flags like go test.
```

I'm not sure I see the reason behind `output`, too. Maybe as a undocumented command for debugging?

**Comment by jeremyschlatter** [comment]
> I'm not sure I see the reason behind output, too. Maybe as a undocumented command for debugging?

Leaving it undocumented sounds good to me. It's mostly an artifact of the early days of godebug when there were no wrapper commands and `godebug` just wrote files in-place. I do find it useful for debugging from time to time, though.
