### ISSUE TITLE
Debug With Multiple GO Files ?

### ISSUE THREAD

**Issue by melihmucuk** [mailgun/godebug#54]
Hi, I'm developing rest api and my project folder looks like :

ProjectFolder
  - main.go
  - handlers.go (breakpoint in here)
  - routes.go
  - etc...

how can I debug my project ? 
`godebug run main.go` didn't work.

**Comment by melihmucuk** [comment]
Oh, I found how to handle it. 

run `godebug build`, this will create projectName.debug file at project folder.

then run debug exec like this `./projectName.debug`

**Comment by jeremyschlatter** [comment]
You can also run `godebug run *.go`. The same is true of the normal `go` command.
