### ISSUE TITLE
Print stack trace

### ISSUE THREAD

**Issue by willfaught** [mailgun/godebug#60]
It would be helpful to print the function stack in times I forget where I am in the current goroutine.

**Comment by glycerine** [comment]
implementation note: debug.PrintStack() prints the stack for you.

**Comment by glycerine** [comment]
http://stackoverflow.com/questions/19094099/how-to-dump-goroutine-stacktraces

Also I see the docs for debug.Stack() say it is deprecated in favor of runtime.Stack(). Not sure which is called by debug.PrintStack() these days.

**Comment by willfaught** [comment]
The full default stack trace with arg values is probably too noisy. Perhaps even just the function names are enough, but I could see how file/line could be helpful too.

If there's ever a feature to examine other stack frames (move up/down the stack), this feature could be reused for that navigation.

**Comment by willfaught** [comment]
Perhaps the goroutine number would be useful too.

**Comment by jeremyschlatter** [comment]
Here's the stack trace you get from runtime.Stack(): http://play.golang.org/p/TzttmeRRD0

The runtime package also exports a [Func](http://golang.org/pkg/runtime/#Func) type that we could use to build a cleaner trace.

**Comment by jeremyschlatter** [comment]
Here's an example of using runtime.Func to make a cleaner stack trace: http://play.golang.org/p/3BiuMP_ocl

**Comment by glycerine** [comment]
I assume that additional information is to allow those debugging the generated assembly to do so. Hence it is valuable (perhaps essential) to some.  I don't find it distracting; I would leave it "uncleaned".
