### ISSUE TITLE
Can't convert variables to other types to inspect with print command

### ISSUE THREAD

**Issue by willfaught** [mailgun/godebug#75]
You can print a variable with an interface type and see its underlying value:

```
> p foo
Foo{Bar: [pointer syntax]}
```

but you can't dig deeper into it to inspect it further (like printing `foo.Bar` above).

It would be awesome if there was a way to convert expressions to other types (or something) in the print command to dig deeper.

Alternatively, pretty print values such that pointer values are dereferenced so you can see what they reference (see e.g. github.com/kr/pretty).

**Comment by glycerine** [comment]
@willfaught , Jeremy is super busy of late, and the code is pretty simple. Why not dig in and implement this?

**Comment by willfaught** [comment]
@glycerine the issue documents the need, it's not a request for anyone specific to do it
