### ISSUE TITLE
godebug not found

### ISSUE THREAD

**Issue by neelmitra** [mailgun/godebug#77]
Hi ,
i installed as per the instructions but it doesn't find the godebug utility on the path. I see there is no godebug .go or exe file on the installed directory too. Am i doing something stupid? 

I am on windows 7 , running from github shell as below. 

$ go get github.com/mailgun/godebug
$ godebug
bash: godebug: command not found

 ~/goworkspace/src/github.com/mailgun/godebug (master)
$ ls -t
z_test.go  testdata/  misc_test.go  lib/  go_15.go  go_14.go  gen/  example/  endtoend_test.go  doc.go  endtoend_cli_test.go  cmd.go  README.md  LICENSE  Godeps/

**Comment by glycerine** [comment]
go get will put the binary in $GOPATH/bin

**Comment by neelmitra** [comment]
ok got it. Thank you.
