### ISSUE TITLE
Add readline support

### ISSUE THREAD

**Issue by jeremyschlatter** [mailgun/godebug#9]

**Comment by glycerine** [comment]
Haven't used this myself, but I think I saw it utilized to good effect in one of the web-login-via-ssh projects. It provides very readline-like functionality (special key handling, emacs-like key-bindings, command history and terminal control) in pure go: 

https://github.com/kless/term/blob/master/readline/doc.go

**Comment by jeremyschlatter** [comment]
Cool, thanks for the pointer.

**Comment by emicklei** [comment]
I have build tools around https://github.com/GeertJohan/go.linenoise.  Maybe this fits as well here.

**Comment by jeremyschlatter** [comment]
After looking through several options I'm planning to go with https://github.com/peterh/liner. I've written the change and just need to finish up testing. Should be ready soon.

**Comment by willfaught** [comment]
+1

**Comment by jmburges** [comment]
Excited!

**Comment by chzyer** [comment]
@jeremyschlatter I will recommend the library I'm working on: https://github.com/chzyer/readline ;)
It works well on darwin/linux/windows, and bring us the zsh-style-readline user experience.
