### ISSUE TITLE
So what's the deal?

### ISSUE THREAD

**Issue by willfaught** [mailgun/godebug#91]
@jeremyschlatter Is godebug abandoned? It would help to just say so.

**Comment by MaxPRafferty** [comment]
Seems like it - dunno why it is still the top google link. Try Delve, it works well for me: https://blog.gopheracademy.com/advent-2015/debugging-with-delve/ 
If youre on osx, its as easy as `brew install go-delve/delve/delve` then `dlv debug` from inside your project directory.

**Comment by willfaught** [comment]
:+1:

**Comment by horkhe** [comment]
I have added deprecation notice at the top of the readme file. Unless @jeremyschlatter or anybody else would like to step in and become a project maintainer.
